extends: stylelint-config-standard
rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - focus-visible
  no-descending-specificity: null
  declaration-colon-newline-after: null
